REGRESSION MODELS AND RMSE

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
train=pd.read_csv('Final_train.csv')
test=pd.read_csv('Final_test.csv')

In [3]:
print(train)

           id gender  age  number_of_kids  date  day   duration
0      979863   MALE   26               2   1.0  3.0   8.066667
1      979863   MALE   26               2   2.0  4.0  10.620833
2      979863   MALE   26               2   3.0  5.0   8.829167
3      979863   MALE   26               2   4.0  6.0   8.116667
4      979863   MALE   26               2   6.0  1.0   9.875000
...       ...    ...  ...             ...   ...  ...        ...
42388  165666   MALE   35               1  17.0  5.0   5.458333
42389  165666   MALE   35               1  18.0  6.0   5.312500
42390  165666   MALE   35               1  19.0  0.0   7.966667
42391  165666   MALE   35               1  20.0  1.0   5.504167
42392  165666   MALE   35               1  21.0  2.0   6.483333

[42393 rows x 7 columns]


ENCODING CATEGORICAL DATA

In [4]:
gender=pd.get_dummies(train.iloc[:,1].values)
days=pd.get_dummies(train.iloc[:,5].values)

In [5]:
train_set=train.drop(['id','gender','day'],axis=1)

In [6]:
train_set=pd.concat([train_set,gender,days],axis=1)


In [7]:
train_set

age  number_of_kids  date   duration  FEMALE  MALE  0.0  1.0  2.0  3.0  \
0       26               2   1.0   8.066667       0     1    0    0    0    1   
1       26               2   2.0  10.620833       0     1    0    0    0    0   
2       26               2   3.0   8.829167       0     1    0    0    0    0   
3       26               2   4.0   8.116667       0     1    0    0    0    0   
4       26               2   6.0   9.875000       0     1    0    1    0    0   
...    ...             ...   ...        ...     ...   ...  ...  ...  ...  ...   
42388   35               1  17.0   5.458333       0     1    0    0    0    0   
42389   35               1  18.0   5.312500       0     1    0    0    0    0   
42390   35               1  19.0   7.966667       0     1    1    0    0    0   
42391   35               1  20.0   5.504167       0     1    0    1    0    0   
42392   35               1  21.0   6.483333       0     1    0    0    1    0   

       4.0  5.0  6.0  
0        0    0    0  
1        1    0    0  
2        0    1    0  
3        0    0    1  
4        0    0    0  
...    ...  ...  ...  
42388    0    1    0  
42389    0    0    1  
42390    0    0    0  
42391    0    0    0  
42392    0    0    0  

[42393 rows x 13 columns]

SPLITTING THE DATASET INTO DV AND IDV:

In [8]:
x=train_set.iloc[:,[0,1,4,5,6,7,8,9,10,11,12]].values
y=train_set.iloc[:,3].values

In [9]:
y

array([ 8.06666667, 10.62083333,  8.82916667, ...,  7.96666667,
        5.50416667,  6.48333333])

SPLITTING THE DATA INTO TRAINING AND TEST SET:

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [11]:
x_train

array([[53,  4,  0, ...,  0,  1,  0],
       [19,  1,  0, ...,  0,  0,  1],
       [71,  2,  1, ...,  0,  0,  0],
       ...,
       [33,  3,  1, ...,  0,  0,  0],
       [29,  0,  0, ...,  0,  0,  1],
       [26,  1,  1, ...,  0,  0,  0]], dtype=int64)

In [12]:
y_test

array([7.16666667, 4.47083333, 5.91666667, ..., 2.79166667, 8.45833333,
       5.2625    ])

FEATURE SCALING:

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,[0,1]]=sc.fit_transform(x_train[:,[0,1]])
x_test[:,[0,1]]=sc.transform(x_test[:,[0,1]])


In [14]:
x_train

array([[ 1,  1,  0, ...,  0,  1,  0],
       [-1,  0,  0, ...,  0,  0,  1],
       [ 2,  0,  1, ...,  0,  0,  0],
       ...,
       [ 0,  1,  1, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  1],
       [ 0,  0,  1, ...,  0,  0,  0]], dtype=int64)

TEST DATASET:

In [15]:
Final_test_data=pd.read_csv('Final_test.csv')

In [16]:
Final_test_data.head()

id      date  online_hours  day gender  age  number_of_kids
0  979863  28/06/17             7    2   MALE   26               2
1  979863  27/06/17             9    1   MALE   26               2
2  979863  26/06/17             9    0   MALE   26               2
3  979863  25/06/17            10    6   MALE   26               2
4  979863  24/06/17             9    5   MALE   26               2

ENCODING CATEGORICAL DATA:

In [17]:
gender_v2=pd.get_dummies(Final_test_data.iloc[:,4].values)
days_v2=pd.get_dummies(Final_test_data.iloc[:,3].values)

In [18]:
test_data2=Final_test_data.drop(['id','gender','day'],axis=1)

In [19]:
test_set2=pd.concat([test_data2,gender_v2,days_v2],axis=1)

In [20]:
train_set

age  number_of_kids  date   duration  FEMALE  MALE  0.0  1.0  2.0  3.0  \
0       26               2   1.0   8.066667       0     1    0    0    0    1   
1       26               2   2.0  10.620833       0     1    0    0    0    0   
2       26               2   3.0   8.829167       0     1    0    0    0    0   
3       26               2   4.0   8.116667       0     1    0    0    0    0   
4       26               2   6.0   9.875000       0     1    0    1    0    0   
...    ...             ...   ...        ...     ...   ...  ...  ...  ...  ...   
42388   35               1  17.0   5.458333       0     1    0    0    0    0   
42389   35               1  18.0   5.312500       0     1    0    0    0    0   
42390   35               1  19.0   7.966667       0     1    1    0    0    0   
42391   35               1  20.0   5.504167       0     1    0    1    0    0   
42392   35               1  21.0   6.483333       0     1    0    0    1    0   

       4.0  5.0  6.0  
0        0    0    0  
1        1    0    0  
2        0    1    0  
3        0    0    1  
4        0    0    0  
...    ...  ...  ...  
42388    0    1    0  
42389    0    0    1  
42390    0    0    0  
42391    0    0    0  
42392    0    0    0  

[42393 rows x 13 columns]

In [21]:
test_set2

date  online_hours  age  number_of_kids  FEMALE  MALE  0  1  2  3  \
0      28/06/17             7   26               2       0     1  0  0  1  0   
1      27/06/17             9   26               2       0     1  0  1  0  0   
2      26/06/17             9   26               2       0     1  1  0  0  0   
3      25/06/17            10   26               2       0     1  0  0  0  0   
4      24/06/17             9   26               2       0     1  0  0  0  0   
...         ...           ...  ...             ...     ...   ... .. .. .. ..   
17495  26/06/17             7   35               1       0     1  1  0  0  0   
17496  25/06/17             7   35               1       0     1  0  0  0  0   
17497  24/06/17            10   35               1       0     1  0  0  0  0   
17498  23/06/17             6   35               1       0     1  0  0  0  0   
17499  22/06/17            10   35               1       0     1  0  0  0  1   

       4  5  6  
0      0  0  0  
1      0  0  0  
2      0  0  0  
3      0  0  1  
4      0  1  0  
...   .. .. ..  
17495  0  0  0  
17496  0  0  1  
17497  0  1  0  
17498  1  0  0  
17499  0  0  0  

[17500 rows x 13 columns]

SPLITTING THE TEST DATASET:

In [22]:
xtest_v2=test_set2.iloc[:,[2,3,4,5,6,7,8,9,10,11,12]].values
ytest_v2=test_set2.iloc[:,1].values

In [23]:
xtest_v2

array([[26,  2,  0, ...,  0,  0,  0],
       [26,  2,  0, ...,  0,  0,  0],
       [26,  2,  0, ...,  0,  0,  0],
       ...,
       [35,  1,  0, ...,  0,  1,  0],
       [35,  1,  0, ...,  1,  0,  0],
       [35,  1,  0, ...,  0,  0,  0]], dtype=int64)

In [24]:
xtest_v2[:,[0,1]]=sc.transform(xtest_v2[:,[0,1]])

In [25]:
xtest_v2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

MULTIPLE LINEAR REGRESSION

In [26]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [27]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[5.26 7.17]
 [4.37 4.47]
 [5.21 5.92]
 ...
 [3.48 2.79]
 [5.51 8.46]
 [3.14 5.26]]


In [28]:
y_pred_ml = regressor.predict(xtest_v2)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_ml.reshape(len(y_pred_ml),1), ytest_v2.reshape(len(ytest_v2),1)),1))

[[ 5.18  7.  ]
 [ 5.21  9.  ]
 [ 5.17  9.  ]
 ...
 [ 6.4  10.  ]
 [ 5.26  6.  ]
 [ 5.04 10.  ]]


In [32]:
from sklearn.metrics import mean_squared_error
from math import sqrt


a2= mean_squared_error(y_test, y_pred)
b2= mean_squared_error(ytest_v2, y_pred_ml)
# taking root of mean squared error
root_mean_squared_error = sqrt(a2)
root_mean_squared_error_ml = sqrt(b2)

In [33]:
print(root_mean_squared_error,root_mean_squared_error_ml)

2.3196262480031624 3.462543113939783


SUPPORT VECTOR REGRESSION

In [35]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train, y_train)

SVR()

In [36]:
y_pred_svr=regressor.predict(x_test)

In [38]:
y_pred_svr2=regressor.predict(xtest_v2)

In [43]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred_svr)

0.1851501296289818

In [45]:
from sklearn.metrics import r2_score
r2_score(ytest_v2,y_pred_svr2)

-0.042591093926604984

In [41]:
from sklearn.metrics import mean_squared_error
from math import sqrt


a_svr= mean_squared_error(y_test, y_pred_svr)
b_svr= mean_squared_error(ytest_v2, y_pred_svr2)
# taking root of mean squared error
root_mean_squared_error_svr = sqrt(a_svr)
root_mean_squared_error_svr1 = sqrt(b_svr)

In [42]:
print(root_mean_squared_error_svr,root_mean_squared_error_svr1)

2.3102904946987834 3.4538408351205447


DECISION TREE REGRESSION

In [48]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(x_train, y_train)

DecisionTreeRegressor(random_state=0)

In [50]:
y_pred_dt=regressor.predict(x_test)

In [51]:
y_pred_dt2=regressor.predict(xtest_v2)

In [52]:
r2_score(y_test,y_pred_dt)

0.19229784078081003

In [54]:
r2_score(ytest_v2,y_pred_dt2)

-0.03283311978826142

In [57]:
a_dt= mean_squared_error(y_test, y_pred_dt)
b_dt2= mean_squared_error(ytest_v2, y_pred_dt2)
# taking root of mean squared error
root_mean_squared_error_dt = sqrt(a_dt)
root_mean_squared_error_dt1 = sqrt(b_dt2)

In [58]:
print(root_mean_squared_error_dt,root_mean_squared_error_dt1)

2.3001354573658115 3.4376399874006456
